const productData = [
  {
    id: 1,
    name: "islomjo1",
    img: "https://via.placeholder.com/350x350",
    price: 200,
    discount: 23200,
    category: "shoes",
  },
  {
    id: 2,
    name: "islomjo2",
    img: "https://via.placeholder.com/350x350",
    price: 100,
    discount: 23200,
    category: "dress",
  },
  {
    id: 3,
    name: "islomjo3",
    img: "https://via.placeholder.com/350x350",
    price: 20,
    discount: 100,
    category: "dress",
  },
  {
    id: 4,
    name: "islomjo3",
    img: "https://via.placeholder.com/350x350",
    price: 900,
    discount: 20,
    category: "shoes",
  },
  {
    id: 5,
    name: "islomjo3",
    img: "https://via.placeholder.com/350x350",
    price: 330,
    discount: 23200,
    category: "shoes",
  },
  {
    id: 6,
    name: "islomjo3",
    img: "https://via.placeholder.com/350x350",
    price: 3120,
    discount: 23200,
    category: "shoes",
  },
  {
    id: 7,
    name: "islomjo3",
    img: "https://via.placeholder.com/350x350",
    price: 40,
    discount: 23200,
    category: "shoes",
  },
  
];
